### PR TITLE
Working PR

### LINKED ISSUE #10: Polling several partitions from the same consumer doesn't work as expected
the following code should poll 3 seperate partitions for new data in a topic, however, this only polls the first partition which `.poll` was called on:

```javascript
var kafkaesque = require('kafkaesque');

var consumer = kafkaesque({
                              brokers: [
                                {host: 'localhost', port: 9093}
                              ],
                              clientId: 'fish',
                              group: 'multiconsume',
                              maxBytes: 2000000
                            });

consumer.tearUp(function() {
  consumer.poll({topic: 'my-replicated-partitioned-topic', partition: 0}, poll);
  consumer.poll({topic: 'my-replicated-partitioned-topic', partition: 1}, poll);
  consumer.poll({topic: 'my-replicated-partitioned-topic', partition: 2}, poll);
  
  var i = 0;
  function poll(err, kafka) {
    console.log('*** in here ', i++);
    if (err) console.log('error', err);

    kafka.on('message', function(offset, message, commit) {
      console.log('received msg for consumer.', 'offset: ' + offset + '.', message.value);
      commit();
    });

    kafka.on('debug', console.log.bind(null, 'debug: '));

    kafka.on('error', function(error) {
      console.log('error', JSON.stringify(error));
    });
  }
});
```

I have investigated and discovered on line 184 of lib/kafkaesque.js you are declaring a global emitter for firing events relating to the partition. This may or may not be related.

Expected behaviour based on this script would be that the `kafka` object passed into the poll function would be a `new` event emitter, not a global one.

### LINKED ISSUE #11: [SUGGESTION] When a params.partition is not specified for the .`poll(params, cb)` function, kafkaesque should poll all partition for a topic
When starting a kafkaesque instance/consumer, the code is as follows:

```javascript
var kafkaesque = require('kafkaesque');

var consumer = kafkaesque({
                              brokers: [
                                {host: 'localhost', port: 9093}
                              ],
                              clientId: 'fish' + i,
                              group: 'cheese',
                              maxBytes: 2000000
                            });

consumer.tearUp(function() {
  consumer.poll({topic: 'some-topic', partition: 0}, function(err, kafka) {
    if (err) console.log('error', err);

    kafka.on('message', function(offset, message, commit) {
      console.log('received msg for consumer.', 'offset: ' + offset + '.', message.value);
      commit();
    });

    kafka.on('debug', console.log.bind(null, 'debug: '));

    kafka.on('error', function(error) {
      console.log('error', JSON.stringify(error));
    });
  });
});
```

Notice how when calling `consumer.poll()`, we specify a partition. My suggestion
would be to allow users to NOT specify a partition, and kafkaesque will auto poll
all partition's in a specific topic.

Currently, if you wanted to poll several partitions in the same topic, you might expect to do it like so:
(NOTE: issue #10 needs to fixed for this to work as expected)

```javascript
var kafkaesque = require('kafkaesque');

var consumer = kafkaesque({
                              brokers: [
                                {host: 'localhost', port: 9093}
                              ],
                              clientId: 'fish',
                              group: 'cheese',
                              maxBytes: 2000000
                            });

consumer.tearUp(function() {
  consumer.poll({topic: 'some-topic', partition: 0}, poll);
  consumer.poll({topic: 'some-topic', partition: 1}, poll);
  .
  .
  .
  consumer.poll({topic: 'some-topic', partition: N}, poll);

  function poll(err, kafka) {
    if (err) console.log('error', err);

    kafka.on('message', function(offset, message, commit) {
      console.log('received msg for consumer.', 'offset: ' + offset + '.', message.value);
      commit();
    });

    kafka.on('debug', console.log.bind(null, 'debug: '));

    kafka.on('error', function(error) {
      console.log('error', JSON.stringify(error));
    });
  }
});
```

### PR DESCRIPTION
**Pull request by thekemkid**
Fixes #10.
Fixes #11.

This commit is the base of my work so far, some refactoring is included and the base file in which I will write tests for specific scenarios. 

This commit fixes a bug where a single consumer couldn't consume several messages which had arrived in its buffer at once. I now loop over the buffer and clean it out before moving on. This fixes #10.

### CODE REVIEW

**Comment by thekemkid** [comment]
Added a commit which fixes #11, you can now leave the partition empty when calling `.poll()` and the callback will automatically poll data for EACH partition.

Example:
```javascript
var kafkaesque = require('kafkaesque');

var consumer = kafkaesque({
                              brokers: [
                                {host: 'localhost', port: 9093}
                              ],
                              clientId: 'fish',
                              group: 'multiconsume',
                              maxBytes: 2000000
                            });

consumer.tearUp(function() {
  consumer.poll({topic: 'my-replicated-partitioned-topic'}, poll);

  var i = 0;
  function poll(err, kafka) {
    var consumer = i++;
    console.log('*** in here ', consumer);
    if (err) console.log('error', err);

    kafka.on('message', function(offset, message, commit) {
      console.log('received msg for consumer of partition: ' + consumer + '.', 'offset: ' + offset + '.', message.value);
      commit();
    });

    kafka.on('debug', console.log.bind(null, 'debug ' + consumer));

    kafka.on('error', function(error) {
      console.log('error', JSON.stringify(error));
    });
  }
});
```

Say 'my-replicated-partitioned-topic' has 3 partitions, then the `poll` function/callback will be called 3 times, where the `kafka` EventEmitter object is PER partition. This allows you to poll all partitions in a topic.

**Comment by mcdonnelldean** [comment]
@pelger this needs test automation and some more tests I think? I have no access to pull this in.

@thekemkid Whats done LGTM but as above I feel a few more tests and at least reporting to travis is needed.

**Comment by thekemkid** [comment]
Ah, this is an outdated pr. Closing and opening a new one, sorry

**Comment by mcdonnelldean** [comment]
👍

**Pull request closed without merging**
